In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer , Embedding , LSTM , TimeDistributed , Dense , Activation , Bidirectional , Conv1D , Dropout
import glob

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


---

# Data Downloading

In [52]:
!gdown --id 1I8MtjQZHeM9kW_mNWFlJIMcW0wIn_dQG

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1I8MtjQZHeM9kW_mNWFlJIMcW0wIn_dQG 



In [ ]:
!unzip /content/LST20-21/LST20.zip

In [4]:
!unzip /content/Datasets/LST20-21/LST20.zip  -d /content/Datasets/LST20/

unzip:  cannot find or open /content/Datasets/LST20-21/LST20.zip, /content/Datasets/LST20-21/LST20.zip.zip or /content/Datasets/LST20-21/LST20.zip.ZIP.


In [33]:
!gdown --id 1LNdjbQ4TqP1cMWM0vNCfIC5lYJFiz58e

Downloading...
From: https://drive.google.com/uc?id=1LNdjbQ4TqP1cMWM0vNCfIC5lYJFiz58e
To: /content/training.csv
100% 87.4M/87.4M [00:00<00:00, 248MB/s]


# Encoding and Decoding Stuff

- At this place we are going to do the encoding and decoding stuff

In [34]:
import pandas as pd
data_df = pd.read_csv("training.csv")
training_df = data_df[["text","POS"]].drop_duplicates(['text']).reset_index()

In [35]:
all_vocab = np.concatenate([training_df["text"].unique(),training_df["POS"].unique() , np.array(['_'])])
len(all_vocab)

48905

In [36]:
idx = 0
encoder = {}
for i in all_vocab :
  encoder[i] = idx
  idx+=1
decoder = {i : v for v,i in encoder.items()}

# **Word2Vec**

In [37]:
!pip install pythainlp

In [13]:
idx2word = decoder
word2idx = {value : key for (key, value) in decoder.items()}


In [14]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from pythainlp.tokenize import word_tokenize
from gensim.models import KeyedVectors
import numpy as np

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

import dill as pickle
import pandas as pd

model_path = 'thwiki_data/models/'

In [15]:
#load into gensim
from pythainlp import word_vector
!wget https://github.com/PyThaiNLP/large-thaiword2vec/releases/download/v0.1/LTW2V_v0.1.bin

Corpus: thai2fit_wv
- Downloading: thai2fit_wv 0.1


100%|██████████| 62452646/62452646 [00:00<00:00, 161146781.76it/s]


--2022-02-16 13:57:30--  https://github.com/PyThaiNLP/large-thaiword2vec/releases/download/v0.1/LTW2V_v0.1.bin
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/376703270/6d785580-cd07-11eb-9f25-ac3fa1ecffa9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220216%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220216T135730Z&X-Amz-Expires=300&X-Amz-Signature=fce9407c82cb2189ee067c423a2ec887f771fa288cae494c388b1dacb7c66287&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=376703270&response-content-disposition=attachment%3B%20filename%3DLTW2V_v0.1.bin&response-content-type=application%2Foctet-stream [following]
--2022-02-16 13:57:31--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/376703270/6d785580-cd07-11eb-9f25-ac3fa1ecffa9?

In [38]:
w2v_model = KeyedVectors.load_word2vec_format('LTW2V_v0.1.bin', binary=True, unicode_errors='ignore')

In [ ]:
w2v_model.get_vector('นะ')

In [39]:
import numpy as np
embedding_dimention = 100

def embedding_matrix_creater(embedding_dimention, word2idx):
    miss = 0

    embedding_matrix = np.zeros((len(word2idx) + 1, embedding_dimention))
    for word, i in word2idx.items():
        embedding_vector = None
        try:
            embedding_vector = w2v_model.get(word)
        except:
            pass
        if embedding_vector is not None:
          # words not found in embedding index will be all-zeros.
          embedding_matrix[i] = embedding_vector
        else:
          miss +=1
    return embedding_matrix
embedding_matrix = embedding_matrix_creater(100, word2idx=word2idx)

In [40]:
from keras.layers import Embedding
EMBEDDING_DIM = 100

word_embedding_layer = Embedding(input_dim=48904, output_dim=100, trainable=True,)
word_embedding_layer.build((None,))
word_embedding_layer.set_weights([embedding_matrix])

# **Encode**

In [41]:
def encode(text) :
  if text in encoder :
    return encoder[text]
  return 48906
def decode(text) :
  if text in decoder : 
    return decoder[text]
  return "_"
def encode_label(text) :
  payload = {'AJ' : 0, 'AV' : 1, 'AX' :2, 'CC' : 3, 'CL' : 4, 'FX' : 5, 'IJ' : 6, 'NG' : 7, 'NN' : 8, 'NU' : 9, 'O' : 10, 'PA' : 11, 'PR' : 12, 'PS' :13, 'PU' :14, 'VV' :15, 'XX' : 16}
  return payload[text]
def decode_label(text) :
  payload = { 0 : 'AJ', 1 : 'AV',  2:'AX' ,  3 : 'CC',  4 : 'CL', 5 : 'FX', 6 : 'IJ', 7 : 'NG', 8 : 'NN', 9 : 'NU', 10 : 'O', 11 : 'PA',  12 : 'PR', 13 :'PS',  14:'PU',  15:'VV', 16 : 'XX'}
  return payload[text]

In [22]:
training_df["e_text"] = training_df["text"].apply(lambda x : encode(x))
training_df["e_pos"] = training_df["POS"].apply(lambda x : encode_label(x))

In [23]:
training_df

index          text POS  e_text  e_pos
0            0         แชมป์  NN       0      8
1            1  สิงห์คลาสสิก  NN       1      8
2            2          กวาด  VV       2     15
3            3        รางวัล  NN       3      8
4            4           แสน  NU       4      9
...        ...           ...  ..     ...    ...
48883  2710324         พ.ต.อ  NN   48883      8
48884  2710326       สรายุทธ  NN   48884      8
48885  2710328     สงวนโภคัย  NN   48885      8
48886  2710359         พรุ้ง  NN   48886      8
48887  2710757   เปรมประชากร  NN   48887      8

[48888 rows x 5 columns]

# Creating the Train Set 

- in this part we are going to create the train set base on the batch size so that we don't have to do padding with our data

In [59]:
words_payload = []
labels_payload = []

for i in glob.glob('/content/LST20/train/*') :
  fp = open(i,"r")
  for line in fp.readlines() :
    if line == '\n' :
      continue
    else :
      data_ = line[:-2].split("\t")
      words_payload.append(data_[0])
      labels_payload.append(data_[1])

In [60]:
words_payload_encoded = [encode(r) for r in words_payload]
labels_payload_encoded = [encode_label(r) for r in labels_payload]

In [62]:
encode_label

<function __main__.encode_label>

In [63]:
BATCH_SIZE = 128

In [64]:
np_word_encoded = np.array(words_payload_encoded)
np_label_encoded = np.array(labels_payload_encoded)

In [65]:
print(len(np_word_encoded))

2714726


In [66]:
batched_word = np_word_encoded[:-1*(np_word_encoded.shape[0]%BATCH_SIZE)].reshape(-1,BATCH_SIZE)
batched_label = np_label_encoded[:-1*(np_label_encoded.shape[0]%BATCH_SIZE)].reshape(-1,BATCH_SIZE)

In [ ]:
words_payload_encoded

In [68]:
np_word_encoded

array([ 6668, 23481,   108, ...,   214,  1983,   526])

In [69]:
batched_word

array([[ 6668, 23481,   108, ..., 48904,  6284, 48904],
       [ 6285, 48904,  1018, ..., 48904,   186, 23484],
       [  186, 48904,  8797, ...,  1084,   315,  1712],
       ...,
       [  440,   147,   823, ..., 48904,   186,  7224],
       [48904,  7225,   186, ...,  7234,    19,  7235],
       [  111, 48904,   630, ...,  1274,  1541,   448]])

# Create Validation Set

In [70]:
words_payload_valid = []
labels_payload_valid = []

for i in glob.glob('/content/LST20/eval/*') :
  fp = open(i,"r")
  for line in fp.readlines() :
    if line == '\n' :
      continue
    else :
      data_ = line[:-2].split("\t")
      words_payload_valid.append(data_[0])
      labels_payload_valid.append(data_[1])

In [71]:
words_payload_encoded_valid = [encode(r) for r in words_payload_valid]
labels_payload_encoded_valid = [encode_label(r) for r in labels_payload_valid]

In [72]:
BATCH_SIZE = 128
np_word_encoded_valid = np.array(words_payload_encoded_valid)
np_label_encoded_valid = np.array(labels_payload_encoded_valid)

In [73]:
words_payload_valid

['สอบ',
 'แท็บลอยด์',
 'ดัง',
 'ผู้ดี',
 'แฮ็ก',
 'มือถือ',
 'คน',
 'ดัง',
 'ลอนดอน',
 '-',
 'สอบ',
 'แท็บลอยด์',
 'ดัง',
 'ผู้ดี',
 'แฮ็ก',
 'มือถือ',
 'คน',
 'ดัง',
 '_',
 'เหยื่อ',
 'เป็น',
 'ทั้ง',
 'นักการเมือง',
 'และ',
 'คน',
 'บันเทิง',
 'หลาย',
 'พัน',
 'คน',
 'หนังสือพิมพ์',
 'การ์เดียน',
 'ของ',
 'อังกฤษ',
 'รายงาน',
 'เมื่อ',
 'วัน',
 'พฤหัสบดี',
 '_',
 '(',
 '9',
 '_',
 'ก.ค.',
 ')',
 '_',
 'ว่า',
 '_',
 'ตำรวจ',
 'กำลัง',
 'สอบสวน',
 'ข้อ',
 'กล่าวหา',
 'ว่า',
 'หนังสือพิมพ์นิวส์',
 '_',
 'ออฟ',
 '_',
 'เดอะ',
 '_',
 'เวิลด์',
 '_',
 'หนังสือพิมพ์',
 'ราย',
 'สัปดาห์',
 'ชื่อ',
 'ดัง',
 'ของ',
 'อังกฤษ',
 '_',
 'ได้',
 'แฮ็ก',
 'เข้า',
 'ไป',
 'ยัง',
 'โทรศัพท์',
 'มือถือ',
 'ของ',
 'นักการเมือง',
 'และ',
 'คน',
 'ดัง',
 'หลาย',
 'คน',
 'เพื่อ',
 'ขุดคุ้ย',
 'ข้อมูล',
 'รายงาน',
 'ข่าว',
 'ระบุ',
 'ว่า',
 '_',
 'หนังสือพิมพ์',
 'ฉาว',
 'ที่',
 'บริษัท',
 'นิวส์',
 '_',
 'อินเตอร์เนชั่นแนล',
 '_',
 'กรุ๊ป',
 '_',
 'ของ',
 'นาย',
 'รูเพิร์ต',
 '_',
 'เมอร์ด็อก',
 '_',
 'เจ้

In [74]:
batched_word_valid = np_word_encoded_valid[:-1*(np_word_encoded_valid.shape[0]%BATCH_SIZE)].reshape(-1,BATCH_SIZE)
batched_label_valid = np_label_encoded_valid[:-1*(np_label_encoded_valid.shape[0]%BATCH_SIZE)].reshape(-1,BATCH_SIZE)

In [75]:
batched_label_valid

array([[15,  8, 15, ..., 15,  8,  8],
       [ 3,  8,  8, ...,  8, 14,  8],
       [14,  8,  8, ..., 15, 14,  8],
       ...,
       [15,  3,  5, ...,  8,  0, 14],
       [ 3, 15,  8, ..., 13,  8, 14],
       [ 9, 14,  4, ...,  3, 14,  5]])

In [76]:
batched_word_valid

array([[ 1152, 13183,   132, ...,   473,  1112,   251],
       [  697, 19313, 22031, ..., 13984, 48904, 48906],
       [48904,   215,  3905, ...,  3793,  1317, 48906],
       ...,
       [ 2674,  1491,    20, ...,  3228,  3229, 48904],
       [  199,   430,  2966, ...,    57,   211, 48904],
       [ 4712, 48904,   213, ...,   104, 48904,    20]])

In [77]:
train_dataset = tf.data.Dataset.from_tensor_slices((batched_word, batched_label))
test_dataset = tf.data.Dataset.from_tensor_slices((batched_word_valid, batched_label_valid))

# Model Creation

- In this part I'm going to test of several models

In [78]:
# InputLayer , Embedding , LSTM , TimeDistributed , Dense , Activation
model = Sequential() 
model.add(InputLayer(input_shape=(128,)))
model.add(word_embedding_layer)
model.add(Bidirectional(LSTM(512, return_sequences=True, dropout=0.15, recurrent_dropout=0.15)))
model.add(TimeDistributed(Dense(17)))
model.add(Dropout(0.2))
model.add(Activation('softmax'))
model.compile(optimizer="Adam",loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [79]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 128, 100)          4890400   
                                                                 
 bidirectional (Bidirectiona  (None, 128, 1024)        2510848   
 l)                                                              
                                                                 
 time_distributed (TimeDistr  (None, 128, 17)          17425     
 ibuted)                                                         
                                                                 
 dropout (Dropout)           (None, 128, 17)           0         
                                                                 
 activation (Activation)     (None, 128, 17)           0         
                                                                 
Total params: 7,418,673
Trainable params: 7,418,673
Non-

In [ ]:
model.fit(batched_word , batched_label , epochs=5,validation_data=(batched_word_valid,batched_label_valid))

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


663/663 [==============================] - 1014s 2s/step - loss: 0.7821 - accuracy: 0.7131 - val_loss: 0.1801 - val_accuracy: 0.9430
Epoch 2/5
182/663 [=======>......................] - ETA: 12:03 - loss: 0.4368 - accuracy: 0.8002

In [ ]:
z = model.predict(batched_word_valid)
s = np.argmax(z , axis = 2)

In [ ]:
func_ = np.vectorize(lambda x : decode_label(x))
s = func_(s)


In [ ]:
func_ = np.vectorize(lambda x : decode(x))

In [ ]:
print(s[0])
print(batched_label_valid[0])

[ 8  8 14 14 15 14  8 15  8  8 13  8  5 15  8 14  8  2 15  8  3 15  1  8
  8  8  8  8 14 15 14  8]
[ 8  8 14 14 15 14  8 15  8  8 13  8  5 15  8 14  8  2 15  8  3 15 13  8
  8  8  8  8 14 15 14  8]


#Submission Download

In [ ]:
!gdown --id 1cwlaGd-l1yFqT7LctDqxT5ikpJj0vx_g

Downloading...
From: https://drive.google.com/uc?id=1cwlaGd-l1yFqT7LctDqxT5ikpJj0vx_g
To: /content/pos_test.txt.zip
100% 249k/249k [00:00<00:00, 80.8MB/s]


In [ ]:
!unzip /content/pos_test.txt.zip -d /content/submission/

Archive:  /content/pos_test.txt.zip
  inflating: /content/submission/pos_test.txt  


In [ ]:
fp = open("pos_test.txt","r")
  

In [ ]:
word_list_submission = []
for line in fp.readlines() :
  if line != '\n' :
    word_list_submission.append(line[:-1])
  else :
    word_list_submission.append('_')

In [ ]:
len(word_list_submission)

103914

In [ ]:
word_list_submission = word_list_submission[:-1]

In [ ]:
len(word_list_submission)

103913

In [ ]:
103913%32

9

In [ ]:
word_list_submission += ['_']*23

In [ ]:
len(word_list_submission)

103936

In [ ]:
print(word_list_submission)

In [ ]:
word_list_submission_encoded = [encode(i) for i in word_list_submission]

In [ ]:
print(word_list_submission_encoded)

[1291, 2286, 771, 6802, 48904, 5963, 21614, 108, 273, 27, 1818, 27, 4770, 1908, 19, 211, 48904, 23207, 48904, 213, 199, 430, 211, 771, 378, 76, 206, 48904, 48906, 4060, 3429, 48906, 152, 48906, 120, 86, 87, 377, 48904, 76, 48904, 857, 48904, 1715, 7346, 213, 48904, 498, 4136, 2086, 12618, 4060, 1866, 48906, 9373, 657, 48906, 1841, 117, 198, 1068, 3617, 4068, 120, 86, 27, 48904, 87, 41, 377, 357, 3770, 59, 24, 388, 86, 76, 662, 273, 519, 152, 1865, 123, 1868, 2154, 628, 372, 12626, 48904, 1588, 572, 2074, 1038, 1494, 397, 2481, 530, 244, 1866, 48904, 207, 76, 209, 210, 1443, 34713, 48904, 34714, 498, 4136, 2086, 12618, 448, 257, 273, 552, 1866, 123, 1865, 1866, 19, 48906, 55, 5283, 104, 266, 20, 2792, 147, 728, 48904, 1164, 657, 104, 6843, 1866, 48906, 289, 25, 6843, 1866, 414, 939, 148, 3552, 25, 390, 147, 1870, 41, 377, 308, 1028, 41, 385, 433, 24, 1664, 48904, 190, 122, 152, 48906, 1036, 271, 1841, 117, 198, 308, 1068, 3617, 4068, 48904, 697, 45, 152, 48906, 378, 2408, 188, 1068, 117

In [ ]:
np_word_list_submission_encoded_batched = np.array(word_list_submission_encoded).reshape(-1,BATCH_SIZE)

In [ ]:
np_word_list_submission_encoded_batched

array([[ 1291,  2286,   771, ...,  4060,  3429, 48906],
       [  152, 48906,   120, ...,  3617,  4068,   120],
       [   86,    27, 48904, ...,  1494,   397,  2481],
       ...,
       [  501,   262,   370, ..., 48904,   152,   501],
       [   75,    29,   266, ...,   108,   566,   448],
       [  271,    19,    19, ..., 48904, 48904, 48904]])

## submiss

In [ ]:
z = model.predict(np_word_list_submission_encoded_batched)

NameError: name 'np_word_list_submission_encoded_batched' is not defined

In [ ]:
print(z.shape)

(3248, 32, 17)


In [ ]:
s = np.argmax(z,axis=2)

In [ ]:
func2_ = np.vectorize(lambda x : decode_label(x))

In [ ]:
datum = func2_(s)

In [ ]:
datum

array([['CC', 'NN', 'VV', ..., 'VV', 'VV', 'NN'],
       ['VV', 'NN', 'VV', ..., 'CL', 'CL', 'VV'],
       ['NN', 'PS', 'PU', ..., 'NN', 'VV', 'VV'],
       ...,
       ['FX', 'NN', 'NN', ..., 'PU', 'VV', 'FX'],
       ['VV', 'NN', 'PS', ..., 'AX', 'VV', 'CC'],
       ['VV', 'PS', 'PS', ..., 'PU', 'PU', 'PU']], dtype='<U2')

In [ ]:
s = datum.flatten()

In [ ]:
x = s.tolist()[:-23]
print(len(x))

103913


In [ ]:
x

['CC',
 'NN',
 'VV',
 'NN',
 'PU',
 'NN',
 'NU',
 'AX',
 'VV',
 'NN',
 'NN',
 'CC',
 'NN',
 'NN',
 'PS',
 'NN',
 'PU',
 'NU',
 'PU',
 'CL',
 'CC',
 'VV',
 'NN',
 'VV',
 'AJ',
 'NU',
 'CL',
 'PU',
 'NN',
 'VV',
 'VV',
 'NN',
 'VV',
 'NN',
 'VV',
 'NN',
 'NU',
 'NN',
 'PU',
 'NU',
 'PU',
 'NN',
 'PU',
 'NU',
 'NU',
 'CL',
 'PU',
 'NN',
 'NN',
 'VV',
 'NN',
 'VV',
 'NN',
 'NN',
 'VV',
 'VV',
 'NN',
 'NU',
 'NN',
 'PS',
 'NU',
 'CL',
 'CL',
 'VV',
 'NN',
 'PS',
 'PU',
 'NU',
 'PS',
 'NN',
 'VV',
 'NN',
 'NU',
 'CL',
 'AV',
 'NN',
 'NU',
 'VV',
 'PS',
 'AX',
 'VV',
 'NN',
 'CC',
 'NN',
 'NN',
 'AJ',
 'PU',
 'VV',
 'PU',
 'VV',
 'NN',
 'VV',
 'VV',
 'NN',
 'VV',
 'VV',
 'NN',
 'VV',
 'NN',
 'PU',
 'PU',
 'NU',
 'NN',
 'PU',
 'NN',
 'NN',
 'PU',
 'NN',
 'NN',
 'NN',
 'VV',
 'NN',
 'CC',
 'NN',
 'PS',
 'NN',
 'NN',
 'CC',
 'NN',
 'NN',
 'PS',
 'NN',
 'NN',
 'NN',
 'CC',
 'PS',
 'FX',
 'VV',
 'NN',
 'NN',
 'PU',
 'AV',
 'VV',
 'CC',
 'NN',
 'NN',
 'NN',
 'CC',
 'VV',
 'NN',
 'NN',
 'NN',
 'VV',

In [ ]:
submission_df = pd.read_csv("/content/pos_sample_submission.csv")

In [ ]:
submission_df.Predicted = x

In [ ]:
submission_df

Id Predicted
0            1        CC
1            2        NN
2            3        VV
3            4        NN
4            5        PU
...        ...       ...
103908  103909        VV
103909  103910        VV
103910  103911        VV
103911  103912        FX
103912  103913        VV

[103913 rows x 2 columns]

In [ ]:
submission_df.to_csv("submission.csv",index=False)

# Submission

In [ ]:
model.save('weight.h5')